// src/App.tsx
import { useState, useEffect, useCallback } from "react";
import { useTranslation } from "react-i18next";
import { open } from "@tauri-apps/plugin-dialog";
import "./App.css";
import { Project } from "./types";
import { scanWorkspace } from "./utils/scanner";
import { useCommandExecutor } from "./hooks/useCommandExecutor";
import Sidebar from "./components/Sidebar";
import ProjectDetails from "./components/ProjectDetails";
import Settings from "./components/Settings";

function App() {
  const { t } = useTranslation();
  const [workspaceRoots, setWorkspaceRoots] = useState<string[]>(() => {
    const saved = localStorage.getItem("workspaceRoots");
    return saved ? JSON.parse(saved) : [];
  });
  const [projects, setProjects] = useState<Project[]>([]);
  const [selectedProjectId, setSelectedProjectId] = useState<string | undefined>();
  const [showSettings, setShowSettings] = useState(false);
  const [isScanning, setIsScanning] = useState(false);

  const {
    logs,
    runningProcesses,
    runningCommands,
    runCommand,
    stopCommand,
  } = useCommandExecutor();

  const handleRefresh = useCallback(async () => {
    if (workspaceRoots.length === 0) {
      setProjects([]);
      return;
    }
    setIsScanning(true);
    try {
      const allDetectedProjects: Project[] = [];
      for (const root of workspaceRoots) {
        const detected = await scanWorkspace(root);
        allDetectedProjects.push(...detected);
      }

      // Filter out duplicate paths (just in case)
      const uniqueProjects = allDetectedProjects.filter(
        (project, index, self) =>
          index === self.findIndex((p) => p.id === project.id)
      );

      setProjects(uniqueProjects);
      if (uniqueProjects.length > 0 && !selectedProjectId) {
        setSelectedProjectId(uniqueProjects[0].id);
      }
    } catch (error) {
      console.error("Failed to scan workspaces", error);
    } finally {
      setIsScanning(false);
    }
  }, [workspaceRoots, selectedProjectId]);

  useEffect(() => {
    handleRefresh();
    localStorage.setItem("workspaceRoots", JSON.stringify(workspaceRoots));
  }, [workspaceRoots, handleRefresh]);

  const handleSelectWorkspace = async () => {
    const selected = await open({
      directory: true,
      multiple: false,
    });
    if (selected && typeof selected === "string") {
      if (!workspaceRoots.includes(selected)) {
        setWorkspaceRoots((prev) => [...prev, selected]);
      }
    }
  };

  const selectedProject = projects.find((p) => p.id === selectedProjectId);

  if (workspaceRoots.length === 0) {
    return (
      <div className="empty-state">
        <h1>Tauri Workspace Launcher</h1>
        <button onClick={handleSelectWorkspace} className="primary-button">
          {t("selectWorkspace")}
        </button>
      </div>
    );
  }

  return (
    <div className="app-container">
      <Sidebar
        projects={projects}
        selectedProjectId={selectedProjectId}
        onSelectProject={setSelectedProjectId}
        onRefresh={handleRefresh}
        onOpenSettings={() => setShowSettings(true)}
      />
      <main className="main-content">
        {selectedProject ? (
          <ProjectDetails
            project={selectedProject}
            logs={logs[selectedProject.id] || []}
            isRunning={!!runningProcesses[selectedProject.id]}
            runningCommand={runningCommands[selectedProject.id]}
            onRunCommand={(program, args) =>
              runCommand(selectedProject.id, selectedProject.path, program, args)
            }
            onStopCommand={() => stopCommand(selectedProject.id)}
          />
        ) : (
          <div className="no-selection">
            {projects.length > 0 ? (
              <p>{t("selectAProject")}</p>
            ) : isScanning ? (
              <p>Scanning...</p>
            ) : (
              <p>{t("noProjectsFound")}</p>
            )}
          </div>
        )}
      </main>

      {showSettings && (
        <Settings
          workspaceRoots={workspaceRoots}
          onWorkspaceRootsChange={setWorkspaceRoots}
          onClose={() => setShowSettings(false)}
        />
      )}
    </div>
  );
}

export default App;

// src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { _, isLoading } from 'svelte-i18n';
  import { open } from '@tauri-apps/plugin-dialog';
  import type { Project } from './lib/types';
  import { scanWorkspace } from './lib/utils/scanner';
  import Sidebar from './lib/components/Sidebar.svelte';
  import ProjectDetails from './lib/components/ProjectDetails.svelte';
  import Settings from './lib/components/Settings.svelte';
  import "./i18n";

  let workspaceRoots: string[] = JSON.parse(localStorage.getItem('workspaceRoots') || '[]');
  let projects: Project[] = [];
  let selectedProjectId: string | undefined;
  let showSettings = false;
  let isScanning = false;

  async function handleRefresh() {
    if (workspaceRoots.length === 0) {
      projects = [];
      return;
    }
    isScanning = true;
    try {
      const allDetectedProjects: Project[] = [];
      for (const root of workspaceRoots) {
        const detected = await scanWorkspace(root);
        allDetectedProjects.push(...detected);
      }

      projects = allDetectedProjects.filter(
        (project, index, self) =>
          index === self.findIndex((p) => p.id === project.id)
      );

      if (projects.length > 0 && !selectedProjectId) {
        selectedProjectId = projects[0].id;
      }
    } catch (error) {
      console.error("Failed to scan workspaces", error);
    } finally {
      isScanning = false;
    }
  }

  $: {
    localStorage.setItem('workspaceRoots', JSON.stringify(workspaceRoots));
    handleRefresh();
  }

  async function handleSelectWorkspace() {
    const selected = await open({
      directory: true,
      multiple: false,
    });
    if (selected && typeof selected === "string") {
      if (!workspaceRoots.includes(selected)) {
        workspaceRoots = [...workspaceRoots, selected];
      }
    }
  }

  $: selectedProject = projects.find((p) => p.id === selectedProjectId);
</script>

{#if $isLoading}
  <div class="h-screen w-screen flex items-center justify-center bg-base-100">
    <span class="loading loading-spinner loading-lg"></span>
  </div>
{:else}
  <main class="h-screen w-screen flex bg-base-100 overflow-hidden text-base-content">
    {#if workspaceRoots.length === 0}
      <div class="flex-1 flex flex-col items-center justify-center space-y-6 text-center px-4">
        <h1 class="text-4xl font-extrabold tracking-tight">Tauri Workspace Launcher</h1>
        <button class="btn btn-primary btn-lg" on:click={handleSelectWorkspace}>
          {$_('selectWorkspace')}
        </button>
      </div>
    {:else}
      <Sidebar
        {projects}
        {selectedProjectId}
        {isScanning}
        onSelectProject={(id) => selectedProjectId = id}
        onRefresh={handleRefresh}
        onOpenSettings={() => showSettings = true}
      />
      <div class="flex-1 overflow-hidden">
        {#if selectedProject}
          <ProjectDetails project={selectedProject} />
        {:else}
          <div class="h-full flex items-center justify-center text-base-content/50 italic">
            {#if projects.length > 0}
              {$_('selectAProject')}
            {:else if isScanning}
              <span class="loading loading-dots loading-lg"></span>
            {:else}
              {$_('noProjectsFound')}
            {/if}
          </div>
        {/if}
      </div>
    {/if}

    {#if showSettings}
      <Settings
        {workspaceRoots}
        onWorkspaceRootsChange={(roots) => workspaceRoots = roots}
        onClose={() => showSettings = false}
      />
    {/if}
  </main>
{/if}
